### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by chezwhite** [aslushnikov/latex-online#30]
Hi,
I wanted to use the API on my development Angular 4 application, so the origin is http://localhost:4200, but I'm being blocked by your server's CORS policy. I also tried other two domains I have and I've been blocked too. Is this something you want? or am I missing something :/
Thanks.

**Comment by aslushnikov** [comment]
Hi Andrea,

Indeed, CORS is not enabled since there's been no need - and no good use case. 

Would `iframe` work for you instead? If not, could you please share a bit of details about your project - why would you need to fetch PDFs via ajax? It might be an interesting use case we didn't think about.

**Comment by chezwhite** [comment]
Hi, 

Well I want to generate a LaTex PDF based on a pool of questions and answers to create a multiple choice test, so of course I can just do it on the server side. But I was trying your API in case the user can preview the PDF, maybe make more changes and finally upload the array of questions and answers to the server.

**Comment by aslushnikov** [comment]
I see, thanks! I did a simple [pdf generator](http://aslushnikov.github.io/latex-online/examples/pdfgenerator.html) to illustrate iframe approach - would it work for you?

**Comment by chezwhite** [comment]
Oh I see, yes that can perfectly work. Thank you!

**Comment by NachoCasta** [comment]
Hi, im having a similar issue.

What I would like to do is to fetch the pdf via "fetch" and then download it on the users browser, instead of making them open another tab with the link to the API, so that users would be able to download it without having to leave the page.

Is there any way of doing this?

Thanks!
