### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by gcarcassi** [aslushnikov/latex-online#66]
Hi!

First of all, thanks for the outstanding service! Both the idea and the implementation are great!

Yesterday evening I saw that the server
https://latexonline.cc/
is down. Just wanted to make sure you are aware of it and, if so, whether it's down because you stopped supporting it.

Thanks!
Gabriele

**Comment by aslushnikov** [comment]
Damn! Thank you so much for the heads up!

I'm sorry about that - will fix it shortly

**Comment by aeifn** [comment]
if necessary I can provide an additional server for the project

**Comment by aslushnikov** [comment]
@gcarcassi Both `https://latexonline.cc` and `https://texlive2020.latexonline.cc` are back. The root cause is fixed as well, so this kind of downtime won't happen again.

> if necessary I can provide an additional server for the project

@aeifn Thank you for the suggestion! I don't have load-balancing for the compilations at the moment, so I can't just use the server. But this is something I plan to add in future - so I might get back to you :-) 

Alternatively, if you're willing to host the service yourself, I'll be happy to refer to your deployment from the documentation!

**Comment by gcarcassi** [comment]
@aslushnikov Great!!! I am glad I filed this then! :-) Thanks again for all your work, I really appreciate it!
